export interface HexacoItem { n: number; text: string; reverse: boolean; factor: string; facet: string }

/**
 * 60-item IPIP six-factor work-style inventory (10 items per HEXACO construct).
 * Public-domain IPIP meanings (Ashton, Lee & Goldberg, 2007 / ipip.ori.org),
 * written as complete first-person statements for agree/disagree rating.
 * Not HEXACO-PI-R publisher wording.
 */
export const HEXACO_ITEMS: HexacoItem[] = [
  { n: 1, text: "I don't pretend to be more impressive than I really am.", reverse: false, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 2, text: "I begin to panic when there is danger.", reverse: false, factor: "Emotionality", facet: "Fearfulness" },
  { n: 3, text: "I talk a lot in most conversations.", reverse: false, factor: "Extraversion", facet: "Expressiveness" },
  { n: 4, text: "I try to forgive and forget when someone wrongs me.", reverse: false, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 5, text: "I usually keep my things tidy.", reverse: false, factor: "Conscientiousness", facet: "Organization" },
  { n: 6, text: "I believe art is important in life.", reverse: false, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 7, text: "I use flattery to get ahead.", reverse: true, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 8, text: "I face danger confidently.", reverse: true, factor: "Emotionality", facet: "Fearfulness" },
  { n: 9, text: "I don't talk much when I'm with other people.", reverse: true, factor: "Extraversion", facet: "Expressiveness" },
  { n: 10, text: "I hold a grudge when people have hurt me.", reverse: true, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 11, text: "I leave a mess in my living space.", reverse: true, factor: "Conscientiousness", facet: "Organization" },
  { n: 12, text: "I do not like art.", reverse: true, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 13, text: "I would never take things that aren't mine.", reverse: false, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 14, text: "I worry about things a lot.", reverse: false, factor: "Emotionality", facet: "Anxiety" },
  { n: 15, text: "I feel comfortable around people.", reverse: false, factor: "Extraversion", facet: "Social Boldness" },
  { n: 16, text: "I accept people as they are.", reverse: false, factor: "Agreeableness", facet: "Gentleness" },
  { n: 17, text: "I work hard at what I do.", reverse: false, factor: "Conscientiousness", facet: "Diligence" },
  { n: 18, text: "I am interested in science.", reverse: false, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 19, text: "I cheat to get ahead.", reverse: true, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 20, text: "I rarely worry.", reverse: true, factor: "Emotionality", facet: "Anxiety" },
  { n: 21, text: "I would be afraid to give a speech in public.", reverse: true, factor: "Extraversion", facet: "Social Boldness" },
  { n: 22, text: "I find fault with nearly everything.", reverse: true, factor: "Agreeableness", facet: "Gentleness" },
  { n: 23, text: "I do just enough work to get by.", reverse: true, factor: "Conscientiousness", facet: "Diligence" },
  { n: 24, text: "I avoid difficult reading material.", reverse: true, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 25, text: "I would not enjoy being a famous celebrity.", reverse: false, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 26, text: "I often need reassurance from other people.", reverse: false, factor: "Emotionality", facet: "Dependence" },
  { n: 27, text: "I make friends easily.", reverse: false, factor: "Extraversion", facet: "Sociability" },
  { n: 28, text: "I am good at taking advice.", reverse: false, factor: "Agreeableness", facet: "Flexibility" },
  { n: 29, text: "I pay close attention to details.", reverse: false, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 30, text: "I have a vivid imagination.", reverse: false, factor: "Openness to Experience", facet: "Creativity" },
  { n: 31, text: "I love luxury.", reverse: true, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 32, text: "I am seldom bothered by the suffering of strangers.", reverse: true, factor: "Emotionality", facet: "Sentimentality" },
  { n: 33, text: "I keep other people at a distance.", reverse: true, factor: "Extraversion", facet: "Sociability" },
  { n: 34, text: "I am hard to convince.", reverse: true, factor: "Agreeableness", facet: "Flexibility" },
  { n: 35, text: "I pay too little attention to details.", reverse: true, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 36, text: "I do not have a good imagination.", reverse: true, factor: "Openness to Experience", facet: "Creativity" },
  { n: 37, text: "I don't think of myself as better than other people.", reverse: false, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 38, text: "I feel other people's emotions.", reverse: false, factor: "Emotionality", facet: "Sentimentality" },
  { n: 39, text: "I am usually active and full of energy.", reverse: false, factor: "Extraversion", facet: "Liveliness" },
  { n: 40, text: "I rarely get irritated.", reverse: false, factor: "Agreeableness", facet: "Patience" },
  { n: 41, text: "I make plans and stick to them.", reverse: false, factor: "Conscientiousness", facet: "Prudence" },
  { n: 42, text: "I often go against the usual way of doing things.", reverse: false, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 43, text: "I believe I am better than other people.", reverse: true, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 44, text: "I seldom get emotional.", reverse: true, factor: "Emotionality", facet: "Sentimentality" },
  { n: 45, text: "I often feel blue.", reverse: true, factor: "Extraversion", facet: "Liveliness" },
  { n: 46, text: "I get angry easily.", reverse: true, factor: "Agreeableness", facet: "Patience" },
  { n: 47, text: "I jump into things without thinking.", reverse: true, factor: "Conscientiousness", facet: "Prudence" },
  { n: 48, text: "I like to be thought of as a normal kind of person.", reverse: true, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 49, text: "I would never cheat on my taxes.", reverse: false, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 50, text: "I get stressed out easily.", reverse: false, factor: "Emotionality", facet: "Anxiety" },
  { n: 51, text: "I am often the life of the party.", reverse: false, factor: "Extraversion", facet: "Expressiveness" },
  { n: 52, text: "I am inclined to forgive others.", reverse: false, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 53, text: "I get chores done right away.", reverse: false, factor: "Conscientiousness", facet: "Organization" },
  { n: 54, text: "I enjoy intellectual games.", reverse: false, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 55, text: "I boast about my strengths.", reverse: true, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 56, text: "I am willing to take risks.", reverse: true, factor: "Emotionality", facet: "Fearfulness" },
  { n: 57, text: "I keep in the background in groups.", reverse: true, factor: "Extraversion", facet: "Social Boldness" },
  { n: 58, text: "I lose my temper.", reverse: true, factor: "Agreeableness", facet: "Patience" },
  { n: 59, text: "I act impulsively when something is bothering me.", reverse: true, factor: "Conscientiousness", facet: "Prudence" },
  { n: 60, text: "I love to think up new ways of doing things.", reverse: false, factor: "Openness to Experience", facet: "Creativity" },
];

export const HEXACO_FACTORS = ["Honesty-Humility","Emotionality","Extraversion","Agreeableness","Conscientiousness","Openness to Experience"] as const;
export const HEXACO_FACETS: Record<string, string[]> = {
  "Honesty-Humility": ["Sincerity", "Fairness", "Greed Avoidance", "Modesty"],
  "Emotionality": ["Fearfulness", "Anxiety", "Dependence", "Sentimentality"],
  "Extraversion": ["Expressiveness", "Social Boldness", "Sociability", "Liveliness"],
  "Agreeableness": ["Forgiveness", "Gentleness", "Flexibility", "Patience"],
  "Conscientiousness": ["Organization", "Diligence", "Perfectionism", "Prudence"],
  "Openness to Experience": ["Aesthetic Appreciation", "Inquisitiveness", "Creativity", "Unconventionality"],
};
