export interface HexacoItem { n: number; text: string; reverse: boolean; factor: string; facet: string }

/**
 * 60-item IPIP six-factor work-style inventory (10 items per HEXACO construct).
 * Item text from the International Personality Item Pool (public domain).
 * Ashton, M. C., Lee, K., & Goldberg, L. R. (2007). The IPIP–HEXACO scales.
 * https://ipip.ori.org/newHEXACO_PI_key.htm — commercial use allowed without permission.
 * Not a proprietary publisher form — IPIP public-domain items only.
 */
export const HEXACO_ITEMS: HexacoItem[] = [
  { n: 1, text: "Don't pretend to be more than I am.", reverse: false, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 2, text: "Begin to panic when there is danger.", reverse: false, factor: "Emotionality", facet: "Fearfulness" },
  { n: 3, text: "Talk a lot.", reverse: false, factor: "Extraversion", facet: "Expressiveness" },
  { n: 4, text: "Try to forgive and forget.", reverse: false, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 5, text: "Keep things tidy.", reverse: false, factor: "Conscientiousness", facet: "Organization" },
  { n: 6, text: "Believe in the importance of art.", reverse: false, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 7, text: "Use flattery to get ahead.", reverse: true, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 8, text: "Face danger confidently.", reverse: true, factor: "Emotionality", facet: "Fearfulness" },
  { n: 9, text: "Don't talk a lot.", reverse: true, factor: "Extraversion", facet: "Expressiveness" },
  { n: 10, text: "Hold a grudge.", reverse: true, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 11, text: "Leave a mess in my room.", reverse: true, factor: "Conscientiousness", facet: "Organization" },
  { n: 12, text: "Do not like art.", reverse: true, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 13, text: "Would never take things that aren't mine.", reverse: false, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 14, text: "Worry about things.", reverse: false, factor: "Emotionality", facet: "Anxiety" },
  { n: 15, text: "Feel comfortable around people.", reverse: false, factor: "Extraversion", facet: "Social Boldness" },
  { n: 16, text: "Accept people as they are.", reverse: false, factor: "Agreeableness", facet: "Gentleness" },
  { n: 17, text: "Work hard.", reverse: false, factor: "Conscientiousness", facet: "Diligence" },
  { n: 18, text: "Am interested in science.", reverse: false, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 19, text: "Cheat to get ahead.", reverse: true, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 20, text: "Rarely worry.", reverse: true, factor: "Emotionality", facet: "Anxiety" },
  { n: 21, text: "Would be afraid to give a speech in public.", reverse: true, factor: "Extraversion", facet: "Social Boldness" },
  { n: 22, text: "Find fault with everything.", reverse: true, factor: "Agreeableness", facet: "Gentleness" },
  { n: 23, text: "Do just enough work to get by.", reverse: true, factor: "Conscientiousness", facet: "Diligence" },
  { n: 24, text: "Avoid difficult reading material.", reverse: true, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 25, text: "Would not enjoy being a famous celebrity.", reverse: false, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 26, text: "Need reassurance.", reverse: false, factor: "Emotionality", facet: "Dependence" },
  { n: 27, text: "Make friends easily.", reverse: false, factor: "Extraversion", facet: "Sociability" },
  { n: 28, text: "Am good at taking advice.", reverse: false, factor: "Agreeableness", facet: "Flexibility" },
  { n: 29, text: "Pay attention to details.", reverse: false, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 30, text: "Have a vivid imagination.", reverse: false, factor: "Openness to Experience", facet: "Creativity" },
  { n: 31, text: "Love luxury.", reverse: true, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 32, text: "Am seldom bothered by the apparent suffering of strangers.", reverse: true, factor: "Emotionality", facet: "Sentimentality" },
  { n: 33, text: "Keep others at a distance.", reverse: true, factor: "Extraversion", facet: "Sociability" },
  { n: 34, text: "Am hard to convince.", reverse: true, factor: "Agreeableness", facet: "Flexibility" },
  { n: 35, text: "Pay too little attention to details.", reverse: true, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 36, text: "Do not have a good imagination.", reverse: true, factor: "Openness to Experience", facet: "Creativity" },
  { n: 37, text: "Don't think that I'm better than other people.", reverse: false, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 38, text: "Feel others' emotions.", reverse: false, factor: "Emotionality", facet: "Sentimentality" },
  { n: 39, text: "Am usually active and full of energy.", reverse: false, factor: "Extraversion", facet: "Liveliness" },
  { n: 40, text: "Rarely get irritated.", reverse: false, factor: "Agreeableness", facet: "Patience" },
  { n: 41, text: "Make plans and stick to them.", reverse: false, factor: "Conscientiousness", facet: "Prudence" },
  { n: 42, text: "Swim against the current.", reverse: false, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 43, text: "Believe that I am better than others.", reverse: true, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 44, text: "Seldom get emotional.", reverse: true, factor: "Emotionality", facet: "Sentimentality" },
  { n: 45, text: "Often feel blue.", reverse: true, factor: "Extraversion", facet: "Liveliness" },
  { n: 46, text: "Get angry easily.", reverse: true, factor: "Agreeableness", facet: "Patience" },
  { n: 47, text: "Jump into things without thinking.", reverse: true, factor: "Conscientiousness", facet: "Prudence" },
  { n: 48, text: "Like to be thought of as a normal kind of person.", reverse: true, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 49, text: "Would never cheat on my taxes.", reverse: false, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 50, text: "Get stressed out easily.", reverse: false, factor: "Emotionality", facet: "Anxiety" },
  { n: 51, text: "Am the life of the party.", reverse: false, factor: "Extraversion", facet: "Expressiveness" },
  { n: 52, text: "Am inclined to forgive others.", reverse: false, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 53, text: "Get chores done right away.", reverse: false, factor: "Conscientiousness", facet: "Organization" },
  { n: 54, text: "Enjoy intellectual games.", reverse: false, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 55, text: "Boast about my virtues.", reverse: true, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 56, text: "Am willing to take risks.", reverse: true, factor: "Emotionality", facet: "Fearfulness" },
  { n: 57, text: "Keep in the background.", reverse: true, factor: "Extraversion", facet: "Social Boldness" },
  { n: 58, text: "Lose my temper.", reverse: true, factor: "Agreeableness", facet: "Patience" },
  { n: 59, text: "Act impulsively when something is bothering me.", reverse: true, factor: "Conscientiousness", facet: "Prudence" },
  { n: 60, text: "Love to think up new ways of doing things.", reverse: false, factor: "Openness to Experience", facet: "Creativity" },
];
export const HEXACO_FACTORS = ["Honesty-Humility","Emotionality","Extraversion","Agreeableness","Conscientiousness","Openness to Experience"] as const;
export const HEXACO_FACETS: Record<string, string[]> = {
  "Honesty-Humility": ["Sincerity", "Fairness", "Greed Avoidance", "Modesty"],
  "Emotionality": ["Fearfulness", "Anxiety", "Dependence", "Sentimentality"],
  "Extraversion": ["Expressiveness", "Social Boldness", "Sociability", "Liveliness"],
  "Agreeableness": ["Forgiveness", "Gentleness", "Flexibility", "Patience"],
  "Conscientiousness": ["Organization", "Diligence", "Perfectionism", "Prudence"],
  "Openness to Experience": ["Aesthetic Appreciation", "Inquisitiveness", "Creativity", "Unconventionality"],
};
