export interface HexacoItem { n: number; text: string; reverse: boolean; factor: string; facet: string }
export const HEXACO_ITEMS: HexacoItem[] = [
  { n: 1, text: "I would be quite bored by a visit to an art gallery.", reverse: true, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 2, text: "I clean my office or home quite frequently.", reverse: false, factor: "Conscientiousness", facet: "Organization" },
  { n: 3, text: "I rarely hold a grudge, even against people who have badly wronged me.", reverse: false, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 4, text: "I feel reasonably satisfied with myself overall.", reverse: false, factor: "Extraversion", facet: "Social Self-Esteem" },
  { n: 5, text: "I would feel afraid if I had to travel in bad weather conditions.", reverse: false, factor: "Emotionality", facet: "Fearfulness" },
  { n: 6, text: "If I want something from a person I dislike, I will act very nicely toward that person in order to get it.", reverse: true, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 7, text: "I'm interested in learning about the history and politics of other countries.", reverse: false, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 8, text: "When working, I often set ambitious goals for myself.", reverse: false, factor: "Conscientiousness", facet: "Diligence" },
  { n: 9, text: "People sometimes tell me that I am too critical of others.", reverse: true, factor: "Agreeableness", facet: "Gentleness" },
  { n: 10, text: "I rarely express my opinions in group meetings.", reverse: true, factor: "Extraversion", facet: "Social Boldness" },
  { n: 11, text: "I sometimes can't help worrying about little things.", reverse: false, factor: "Emotionality", facet: "Anxiety" },
  { n: 12, text: "If I knew that I could never get caught, I would be willing to steal a million dollars.", reverse: true, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 13, text: "I would like a job that requires following a routine rather than being creative.", reverse: true, factor: "Openness to Experience", facet: "Creativity" },
  { n: 14, text: "I often check my work over repeatedly to find any mistakes.", reverse: false, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 15, text: "People sometimes tell me that I'm too stubborn.", reverse: true, factor: "Agreeableness", facet: "Flexibility" },
  { n: 16, text: "I avoid making \"small talk\" with people.", reverse: true, factor: "Extraversion", facet: "Sociability" },
  { n: 17, text: "When I suffer from a painful experience, I need someone to make me feel comfortable.", reverse: false, factor: "Emotionality", facet: "Dependence" },
  { n: 18, text: "Having a lot of money is not especially important to me.", reverse: false, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 19, text: "I think that paying attention to radical ideas is a waste of time.", reverse: true, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 20, text: "I make decisions based on the feeling of the moment rather than on careful thought.", reverse: true, factor: "Conscientiousness", facet: "Prudence" },
  { n: 21, text: "People think of me as someone who has a quick temper.", reverse: true, factor: "Agreeableness", facet: "Patience" },
  { n: 22, text: "I am energetic nearly all the time.", reverse: false, factor: "Extraversion", facet: "Liveliness" },
  { n: 23, text: "I feel like crying when I see other people crying.", reverse: false, factor: "Emotionality", facet: "Sentimentality" },
  { n: 24, text: "I am an ordinary person who is no better than others.", reverse: false, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 25, text: "I wouldn't spend my time reading a book of poetry.", reverse: true, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 26, text: "I plan ahead and organize things, to avoid scrambling at the last minute.", reverse: false, factor: "Conscientiousness", facet: "Organization" },
  { n: 27, text: "My attitude toward people who have treated me badly is \"forgive and forget\".", reverse: false, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 28, text: "I think that most people like some aspects of my personality.", reverse: false, factor: "Extraversion", facet: "Social Self-Esteem" },
  { n: 29, text: "I don’t mind doing jobs that involve dangerous work.", reverse: true, factor: "Emotionality", facet: "Fearfulness" },
  { n: 30, text: "I wouldn't use flattery to get a raise or promotion at work, even if I thought it would succeed.", reverse: false, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 31, text: "I enjoy looking at maps of different places.", reverse: false, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 32, text: "I often push myself very hard when trying to achieve a goal.", reverse: false, factor: "Conscientiousness", facet: "Diligence" },
  { n: 33, text: "I generally accept people’s faults without complaining about them.", reverse: false, factor: "Agreeableness", facet: "Gentleness" },
  { n: 34, text: "In social situations, I'm usually the one who makes the first move.", reverse: false, factor: "Extraversion", facet: "Social Boldness" },
  { n: 35, text: "I worry a lot less than most people do.", reverse: true, factor: "Emotionality", facet: "Anxiety" },
  { n: 36, text: "I would be tempted to buy stolen property if I were financially tight.", reverse: true, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 37, text: "I would enjoy creating a work of art, such as a novel, a song, or a painting.", reverse: false, factor: "Openness to Experience", facet: "Creativity" },
  { n: 38, text: "When working on something, I don't pay much attention to small details.", reverse: true, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 39, text: "I am usually quite flexible in my opinions when people disagree with me.", reverse: false, factor: "Agreeableness", facet: "Flexibility" },
  { n: 40, text: "I enjoy having lots of people around to talk with.", reverse: false, factor: "Extraversion", facet: "Sociability" },
  { n: 41, text: "I can handle difficult situations without needing emotional support from anyone else.", reverse: true, factor: "Emotionality", facet: "Dependence" },
  { n: 42, text: "I would like to live in a very expensive, high-class neighborhood.", reverse: true, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 43, text: "I like people who have unconventional views.", reverse: false, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 44, text: "I make a lot of mistakes because I don't think before I act.", reverse: true, factor: "Conscientiousness", facet: "Prudence" },
  { n: 45, text: "I rarely feel anger, even when people treat me quite badly.", reverse: false, factor: "Agreeableness", facet: "Patience" },
  { n: 46, text: "On most days, I feel cheerful and optimistic.", reverse: false, factor: "Extraversion", facet: "Liveliness" },
  { n: 47, text: "When someone I know well is unhappy, I can almost feel that person's pain myself.", reverse: false, factor: "Emotionality", facet: "Sentimentality" },
  { n: 48, text: "I wouldn’t want people to treat me as though I were superior to them.", reverse: false, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 49, text: "If I had the opportunity, I would like to attend a classical music concert.", reverse: false, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 50, text: "People often joke with me about the messiness of my room or desk.", reverse: true, factor: "Conscientiousness", facet: "Organization" },
  { n: 51, text: "If someone has cheated me once, I will always feel suspicious of that person.", reverse: true, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 52, text: "I feel that I am an unpopular person.", reverse: true, factor: "Extraversion", facet: "Social Self-Esteem" },
  { n: 53, text: "When it comes to physical danger, I am very fearful.", reverse: false, factor: "Emotionality", facet: "Fearfulness" },
  { n: 54, text: "If I want something from someone, I will laugh at that person's worst jokes.", reverse: true, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 55, text: "I would be very bored by a book about the history of science and technology.", reverse: true, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 56, text: "Often when I set a goal, I end up quitting without having reached it.", reverse: true, factor: "Conscientiousness", facet: "Diligence" },
  { n: 57, text: "I tend to be lenient in judging other people.", reverse: false, factor: "Agreeableness", facet: "Gentleness" },
  { n: 58, text: "When I'm in a group of people, I'm often the one who speaks on behalf of the group.", reverse: false, factor: "Extraversion", facet: "Social Boldness" },
  { n: 59, text: "I rarely, if ever, have trouble sleeping due to stress or anxiety.", reverse: true, factor: "Emotionality", facet: "Anxiety" },
  { n: 60, text: "I would never accept a bribe, even if it were very large.", reverse: false, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 61, text: "People have often told me that I have a good imagination.", reverse: false, factor: "Openness to Experience", facet: "Creativity" },
  { n: 62, text: "I always try to be accurate in my work, even at the expense of time.", reverse: false, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 63, text: "When people tell me that I’m wrong, my first reaction is to argue with them.", reverse: true, factor: "Agreeableness", facet: "Flexibility" },
  { n: 64, text: "I prefer jobs that involve active social interaction to those that involve working alone.", reverse: false, factor: "Extraversion", facet: "Sociability" },
  { n: 65, text: "Whenever I feel worried about something, I want to share my concern with another person.", reverse: false, factor: "Emotionality", facet: "Dependence" },
  { n: 66, text: "I would like to be seen driving around in a very expensive car.", reverse: true, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 67, text: "I think of myself as a somewhat eccentric person.", reverse: false, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 68, text: "I don’t allow my impulses to govern my behavior.", reverse: false, factor: "Conscientiousness", facet: "Prudence" },
  { n: 69, text: "Most people tend to get angry more quickly than I do.", reverse: false, factor: "Agreeableness", facet: "Patience" },
  { n: 70, text: "People often tell me that I should try to cheer up.", reverse: true, factor: "Extraversion", facet: "Liveliness" },
  { n: 71, text: "I feel strong emotions when someone close to me is going away for a long time.", reverse: false, factor: "Emotionality", facet: "Sentimentality" },
  { n: 72, text: "I think that I am entitled to more respect than the average person is.", reverse: true, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 73, text: "Sometimes I like to just watch the wind as it blows through the trees.", reverse: false, factor: "Openness to Experience", facet: "Aesthetic Appreciation" },
  { n: 74, text: "When working, I sometimes have difficulties due to being disorganized.", reverse: true, factor: "Conscientiousness", facet: "Organization" },
  { n: 75, text: "I find it hard to fully forgive someone who has done something mean to me.", reverse: true, factor: "Agreeableness", facet: "Forgiveness" },
  { n: 76, text: "I sometimes feel that I am a worthless person.", reverse: true, factor: "Extraversion", facet: "Social Self-Esteem" },
  { n: 77, text: "Even in an emergency I wouldn't feel like panicking.", reverse: true, factor: "Emotionality", facet: "Fearfulness" },
  { n: 78, text: "I wouldn't pretend to like someone just to get that person to do favors for me.", reverse: false, factor: "Honesty-Humility", facet: "Sincerity" },
  { n: 79, text: "I’ve never really enjoyed looking through an encyclopedia.", reverse: true, factor: "Openness to Experience", facet: "Inquisitiveness" },
  { n: 80, text: "I do only the minimum amount of work needed to get by.", reverse: true, factor: "Conscientiousness", facet: "Diligence" },
  { n: 81, text: "Even when people make a lot of mistakes, I rarely say anything negative.", reverse: false, factor: "Agreeableness", facet: "Gentleness" },
  { n: 82, text: "I tend to feel quite self-conscious when speaking in front of a group of people.", reverse: true, factor: "Extraversion", facet: "Social Boldness" },
  { n: 83, text: "I get very anxious when waiting to hear about an important decision.", reverse: false, factor: "Emotionality", facet: "Anxiety" },
  { n: 84, text: "I’d be tempted to use counterfeit money, if I were sure I could get away with it.", reverse: true, factor: "Honesty-Humility", facet: "Fairness" },
  { n: 85, text: "I don't think of myself as the artistic or creative type.", reverse: true, factor: "Openness to Experience", facet: "Creativity" },
  { n: 86, text: "People often call me a perfectionist.", reverse: false, factor: "Conscientiousness", facet: "Perfectionism" },
  { n: 87, text: "I find it hard to compromise with people when I really think I’m right.", reverse: true, factor: "Agreeableness", facet: "Flexibility" },
  { n: 88, text: "The first thing that I always do in a new place is to make friends.", reverse: false, factor: "Extraversion", facet: "Sociability" },
  { n: 89, text: "I rarely discuss my problems with other people.", reverse: true, factor: "Emotionality", facet: "Dependence" },
  { n: 90, text: "I would get a lot of pleasure from owning expensive luxury goods.", reverse: true, factor: "Honesty-Humility", facet: "Greed Avoidance" },
  { n: 91, text: "I find it boring to discuss philosophy.", reverse: true, factor: "Openness to Experience", facet: "Unconventionality" },
  { n: 92, text: "I prefer to do whatever comes to mind, rather than stick to a plan.", reverse: true, factor: "Conscientiousness", facet: "Prudence" },
  { n: 93, text: "I find it hard to keep my temper when people insult me.", reverse: true, factor: "Agreeableness", facet: "Patience" },
  { n: 94, text: "Most people are more upbeat and dynamic than I generally am.", reverse: true, factor: "Extraversion", facet: "Liveliness" },
  { n: 95, text: "I remain unemotional even in situations where most people get very sentimental.", reverse: true, factor: "Emotionality", facet: "Sentimentality" },
  { n: 96, text: "I want people to know that I am an important person of high status.", reverse: true, factor: "Honesty-Humility", facet: "Modesty" },
  { n: 97, text: "I have sympathy for people who are less fortunate than I am.", reverse: false, factor: "Altruism", facet: "Altruism" },
  { n: 98, text: "I try to give generously to those in need.", reverse: false, factor: "Altruism", facet: "Altruism" },
  { n: 99, text: "It wouldn’t bother me to harm someone I didn’t like.", reverse: true, factor: "Altruism", facet: "Altruism" },
  { n: 100, text: "People see me as a hard-hearted person.", reverse: true, factor: "Altruism", facet: "Altruism" },
];
export const HEXACO_FACTORS = ["Honesty-Humility","Emotionality","Extraversion","Agreeableness","Conscientiousness","Openness to Experience"] as const;
export const HEXACO_FACETS: Record<string, string[]> = {
  "Honesty-Humility": ["Sincerity", "Fairness", "Greed Avoidance", "Modesty"],
  "Emotionality": ["Fearfulness", "Anxiety", "Dependence", "Sentimentality"],
  "Extraversion": ["Social Self-Esteem", "Social Boldness", "Sociability", "Liveliness"],
  "Agreeableness": ["Forgiveness", "Gentleness", "Flexibility", "Patience"],
  "Conscientiousness": ["Organization", "Diligence", "Perfectionism", "Prudence"],
  "Openness to Experience": ["Aesthetic Appreciation", "Inquisitiveness", "Creativity", "Unconventionality"],
};
